version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "lafaktur"
      MYSQL_USER: "lafaktur"
      MYSQL_PASSWORD: "lafaktur"
      MYSQL_ROOT_PASSWORD: "lafaktur"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - lafaktur-db:/var/lib/mysql

  minio:
    image: "minio/minio:latest"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - "minio-gigzby-data:/data/minio"
    command: minio server /data/minio --console-address ":9090"

volumes:
  lafaktur-db:
