import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { ThemeProvider } from "~/app/_components/theme/theme-provider";
import { cn } from "~/app/_utils/styles-utils";
import { I18nProviderClient } from "~/i18n/client";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export function generateStaticParams() {
  return [{ locale: "en" }];
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body
        className={cn(
          `min-h-screen bg-background font-sans antialiased`,
          inter.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <I18nProviderClient locale={locale}>
            <TRPCReactProvider headers={headers()}>
              {children}
            </TRPCReactProvider>
          </I18nProviderClient>
        </ThemeProvider>
      </body>
    </html>
  );
}
